apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storpool-ssd
provisioner: csi.opennebula.io
parameters:
  datastore_id: '100'
mountOptions:
  - noatime
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

